---
title: "Regression_Ideas"
output: html_document
---

#Just going to use the data to see what different methods of forecasting look like.
```{r Looking at All_Season_Stats}
library(readr)
All_Season_Stats=read_csv("All_Season_Stats.csv")

tail(All_Season_Stats,25)
##The data as it stands could be reorganized, I am going to reorgainzie it by season with an emphasys on player age,so each player will have 5 observations at max.





```
```{r Creating Name}

Name=rep(NA,5*length(All_Season_Stats$Player))#Making the data set full with NA's first, this will have 5 repeated names for each player, all data is total yearly for different stats

i=1 


while(floor(i/5)+1<=length(All_Season_Stats$Player)){###the floor(i/5)+1 always rounds to the first name for the first 5 entries and the second name for the next 5 entries

Name[i]=All_Season_Stats$Player[floor(i/5)+1]
Name[i+1]=All_Season_Stats$Player[floor(i/5)+1]
Name[i+2]=All_Season_Stats$Player[floor(i/5)+1]
Name[i+3]=All_Season_Stats$Player[floor(i/5)+1]
Name[i+4]=All_Season_Stats$Player[floor(i/5)+1]

i=i+5
}
Name=as.factor(Name)
tail(Name,25)##Now names are factors that repeat 5 times in the data set for each name
```




```{r Creating Position}


Pos2=rep(NA,5*length(All_Season_Stats$Player))##This will repeat the position of the player listed in this data set, as I assume nobody changed for simplicity.



##Since my goal for this is the same as with name, to repeat the position 5 times, i will re use my old loop.

j=1 


while(floor(j/5)+1<=length(All_Season_Stats$Pos)){###the floor(j/5)+1 always rounds to the first name for the first 5 entries and the second name for the next 5 entries

Pos2[j]=All_Season_Stats$Pos[floor(j/5)+1]
Pos2[j+1]=All_Season_Stats$Pos[floor(j/5)+1]
Pos2[j+2]=All_Season_Stats$Pos[floor(j/5)+1]
Pos2[j+3]=All_Season_Stats$Pos[floor(j/5)+1]
Pos2[j+4]=All_Season_Stats$Pos[floor(j/5)+1]

j=j+5
}
Pos2=as.factor(Pos2)
tail(Pos2,25)##Now Pos2 is a vector of positions as factors

```

```{r Creating Age}



Age=rep(NA,5*length(All_Season_Stats$Player))##This will end up being a list of ages, starting at current age and going down one for the past years







k=1 


while(floor(k/5)+1<=length(All_Season_Stats$Pos)){###the floor(j/5)+1 always rounds to the first name for the first 5 entries and the second name for the next 5 entries

Age[k]=All_Season_Stats$Age[floor(k/5)+1]###Using the same old loop which repeats entries I edited it so that the following entries after every 5th is reduced by one, so now we should have a list of ages that the players were at during each season
Age[k+1]=All_Season_Stats$Age[floor(k/5)+1]-1
Age[k+2]=All_Season_Stats$Age[floor(k/5)+1]-2
Age[k+3]=All_Season_Stats$Age[floor(k/5)+1]-3
Age[k+4]=All_Season_Stats$Age[floor(k/5)+1]-4

k=k+5
}
tail(Age,25)

```

```{r Finiding year}

##Tm I am not going to use for anaylsys

#I won't be using games played, games started, or minutes played in the analysis

Year=rep(NA,5*length(All_Season_Stats$Player))##This will contain years 2018 through 2014

y=c(2018,2017,2016,2015,2014)
Year=rep(y,length(All_Season_Stats$Player))

tail(Year,25)



```

```{r Finding FG}


FG=rep(NA,5*length(All_Season_Stats$Player))##This will contain a record of fieldgoals made on total in years each year 2014 to 2018

ii=1
while(ii<=(5*length(All_Season_Stats$Player))){
FG[ii]=All_Season_Stats$FG_18[floor(ii/5)+1]
FG[ii+1]=All_Season_Stats$FG_17[floor(ii/5)+1]###Every 5th entry is the field goals for 18, and so on
FG[ii+2]=All_Season_Stats$FG_16[floor(ii/5)+1]
FG[ii+3]=All_Season_Stats$FG_15[floor(ii/5)+1]
FG[ii+4]=All_Season_Stats$FG_14[floor(ii/5)+1]

ii=ii+5
}
FG

```


```{r Finding Bhind_Arc}

#I won't be using field goals attempted

Bhind_Arc=rep(NA,5*length(All_Season_Stats$Player))##This will contain the 3 point field goals made per game through the years.

jj=1
while(jj<=(5*length(All_Season_Stats$Player))){
Bhind_Arc[jj]=All_Season_Stats$`3P_18`[floor(jj/5)+1]
Bhind_Arc[jj+1]=All_Season_Stats$`3P_17`[floor(jj/5)+1]###Every 5th entry is the 3 points made for 18, and so on
Bhind_Arc[jj+2]=All_Season_Stats$`3P_16`[floor(jj/5)+1]
Bhind_Arc[jj+3]=All_Season_Stats$`3P_15`[floor(jj/5)+1]
Bhind_Arc[jj+4]=All_Season_Stats$`3P_14`[floor(jj/5)+1]

jj=jj+5
}
tail(Bhind_Arc,25)


```



```{r finding In_Arc}
In_Arc=rep(NA,length(All_Season_Stats$Player))#This will contain 2 point field goals made total throughout the years



l=1
while(l<=(5*length(All_Season_Stats$Player))){
In_Arc[l]=All_Season_Stats$`2P_18`[floor(l/5)+1]
In_Arc[l+1]=All_Season_Stats$`2P_17`[floor(l/5)+1]###Every 5th entry is the 3 points made for 18, and so on
In_Arc[l+2]=All_Season_Stats$`2P_16`[floor(l/5)+1]
In_Arc[l+3]=All_Season_Stats$`2P_15`[floor(l/5)+1]
In_Arc[l+4]=All_Season_Stats$`2P_14`[floor(l/5)+1]

l=l+5
}
tail(In_Arc,25)

```


```{r finding FreeT}
FreeT=rep(NA,length(All_Season_Stats$Player))##This will contain free throws made total throughout the years

ll=1
while(ll<=(5*length(All_Season_Stats$Player))){
FreeT[ll]=All_Season_Stats$FT_18[floor(ll/5)+1]
FreeT[ll+1]=All_Season_Stats$FT_17[floor(ll/5)+1]###Every 5th entry is the 3 points made for 18, and so on
FreeT[ll+2]=All_Season_Stats$FT_16[floor(ll/5)+1]
FreeT[ll+3]=All_Season_Stats$FT_15[floor(ll/5)+1]
FreeT[ll+4]=All_Season_Stats$FT_14[floor(ll/5)+1]

ll=ll+5
}
tail(FreeT,25)

```

```{r}

OfReb=rep(NA,length(All_Season_Stats$Player))##This will contain offensive rebound made total thruoghout the seasons


```
```{r}
DefReb=rep(NA,length(All_Season_Stats$Player))##This will be like OfReb but for defensive rebounds

##Not going to use total rebounds, as in the shiny app a user can just make OfReb and DefReb the same for this result

Assist=rep(NA,length(All_Season_Stats$Player))##This will be the average assists per game in each season

Steal=rep(NA,length(All_Season_Stats$Player))##This will be the average steals per game in each season

Block=rep(NA,length(All_Season_Stats$Player))##This will be the average blocks per game in each season

TOV=rep(NA,length(All_Season_Stats$Player))##This will be the average turnovers per game in each season

Fouls=rep(NA,length(All_Season_Stats$Player))##This will be the average fouls per game in each season

Points=rep(NA,length(All_Season_Stats$Player))##This will be the average points per game in each season


DatSet=data.frame(Name,Pos2,Age,Year,FG,Bhind_Arc,In_Arc,FreeT,OfReb,DefReb,Assist,Steal,Block,TOV,Fouls,Points)
DatSet

```

